export const aboutMeContentObj = {
  topSection: [
    "With over a decade of experience in the hospitality industry, I bring a unique blend of entrepreneurship, customer service and passion to the tech world.",
    <br />,
    <br />,
    "My journey into software development began during the challenging times of COVID-19, when I launched a web-based wine subscription service. This venture not only demonstrated my entrepreneurial spirit but also ignited my interest in technology and web development.",
    <br />,
  ],
  bottomSection: [
    "Motivated by my business' needs, I embarked on a self-directed learning path, diving deep into web technologies including HTML, CSS, and JavaScript.",
    <wbr />,
    <wbr />,
    " The complexity of web development resonated with me, reminiscent of the intricate detail and breadth of knowledge required to be successful in the fast-paced wine industry.",
    <wbr />,
    <wbr />,
    " My early fascination with computers — from being mesmerized by video games at just two years old — has come full circle, shaping my path in the digital realm.",
    <br />,
    <br />,
    "Today, I combine my extensive background in hospitality, my entrepreneurial journey, and my technical expertise to offer tailored solutions that enhance online businesses, particularly within the food and beverage industry.",
    <wbr />,
    <wbr />,
    " Whether you're looking to scale your brand or create a unique digital presence, I bring a specialized knowledge base and a fresh perspective to help your business thrive.",
    <wbr />,
    <wbr />,
    " Let's connect and explore how we can create value for your brand together!",
    <br />,
    <br />,
    "- Brian Davies",
  ],
};
